use_frameworks!

platform :ios, '9.0'

target 'IPaInfiniteScrollController_Example' do
  pod 'IPaInfiniteScrollController', :path => '../'

  target 'IPaInfiniteScrollController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
